
\newpage
\blandscape

## Session Checks

```{r query_session_round_checks, include=FALSE}
# Query the database to get detailed session information
session_round_checks <- dbGetQuery(conn, paste0("
WITH last_session AS (
    SELECT session_id
    FROM rounds
    ORDER BY started_at DESC
    LIMIT 1
)
SELECT 
  rc.round_id, 
  rc.check_time, 
  rc.outcome_valid, 
  rc.green_pecks_valid, 
  rc.red_pecks_valid, 
  rc.feedback_period_valid, 
  rc.pecks_until_warning_valid, 
  rc.quarter_valid
FROM round_checks rc
JOIN rounds r ON rc.round_id = r.round_id
WHERE r.session_id = '", session_id, "';"))
```

```{r session_round_checks_table, echo=FALSE}
# Set custom column headings
colnames(session_round_checks) <- c("Round ID", "Check Time", "Outcome Valid", "Green Pecks Valid", "Red Pecks Valid", "Feedback Period Valid", "Pecks Until Warning Valid", "Quarter Valid")

# Transpose the session_details table for better readability
kable(session_round_checks, caption = "Session Round Checks") %>%
  kable_styling(font_size = 10) %>%  # Adjust the font size as needed
  column_spec(2:ncol(session_round_checks), width = "5em") # Adjust the width as needed
```


## Database Errors

```{r query_session_errors, include=FALSE}
# Query the database to get errors related to the session
session_errors_query1 <- dbGetQuery(conn, paste0("
  SELECT * 
  FROM errors e
  JOIN rounds r ON e.round_id = r.round_id 
  WHERE r.session_id = '", session_id, "';"))

session_errors_query2 <- dbGetQuery(conn, paste0("
  SELECT * 
  FROM errors 
  WHERE session_id = '", session_id, "';"))

# Combine the results of the two queries
session_errors <- rbind(session_errors_query1, session_errors_query2)

# Get the total count of errors
total_errors <- nrow(session_errors)
```

```{r display_session_errors, echo=FALSE}
# Display the total count of errors found or a message indicating no errors found
if (total_errors > 0) {
  cat(total_errors, "error(s) found\n")
} else {
  cat("No errors found\n")
}
```

\elandscape