---
output: pdf_document
header-includes:
  - \usepackage{pdflscape}
  - \usepackage{geometry}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
params:
  round_id: 'fb4949d6-bc4b-4c8f-8028-4832cf91a75a'
  output_dir: "../data"
  output_name: "round_pecks_distribution.pdf"
  custom_output_name: NULL
---
\blandscape

```{r setup, include=FALSE}
# 2b22b802-64bd-4500-b7fc-2e61f566637e
# e0dfea33-3850-4415-afe7-7498a4dc7f03
# Setup chunk: Load necessary libraries and set session_id parameter
knitr::opts_chunk$set(echo = TRUE)
round_id <- params$round_id
output_dir <- file.path("..", "data")
output_name <- params$output_name
library(DBI)
library(dotenv)
library(knitr)
library(kableExtra)
library(ggforce) # Add this line to load ggforce library
library(mailR) # Add this line to load mailR library

# Set the output file name dynamically if custom_output_name is provided
if (!is.null(params$custom_output_name)) {
    output_name <- params$custom_output_name
} else {
    output_name <- params$output_name
}
output_file <- file.path(params$output_dir, output_name)

run_pecks_analysis <- params$run_pecks_analysis
```

```{r load_env, include=FALSE}
# Load environment variables from .env file
dotenv::load_dot_env(file.path("..", ".env"))
```

```{r get_db_credentials, include=FALSE}
# Get database credentials from environment variables
dsn_database <- Sys.getenv("DB_NAME")
dsn_hostname <- Sys.getenv("DB_HOST")
dsn_port <- Sys.getenv("DB_PORT")
dsn_uid <- Sys.getenv("DB_USER")
dsn_pwd <- Sys.getenv("DB_PASSWORD")
```

```{r connect_db, include=FALSE}
# Connect to the PostgreSQL database
tryCatch(
    {
        conn <- dbConnect(
            RPostgres::Postgres(),
            dbname = dsn_database,
            host = dsn_hostname,
            port = dsn_port,
            user = dsn_uid,
            password = dsn_pwd
        )
        cat("Connected successfully!\n")
    },
    error = function(e) {
        cat("Error: ", e$message, "\n")
    }
)
```


```{r pecks, include=FALSE}
# Query the database to get detailed session information

pecks <- dbGetQuery(conn, paste0("
SELECT p.*
FROM pecks p
WHERE p.round_id = '", round_id, "';"))
```

## Session Details

```{r query_session_details, include=FALSE}
# Query the database to get detailed session information
session_details <- dbGetQuery(conn, paste0("
  SELECT
    session_id,
    created_at,
    subject_name,
    reinforcement_ratio,
    warning_hits,
    punishment_duration,
    feed_time,
    total_reinforcements,
    consecutive_warnings_limit,
    warning_alarm_volume,
    warning_display_volume,
    mode_name,
    sessions.mode_id,
    is_spot_on,
    punishment_periodicity,
    warning_duration,
    time_before_warning_signal,
    highlight_warning_signal,
    button_size,
    grace_radius,
    warning_signal_position,
    button_height,
    peck_slide,
    window_height,
    window_width,
    comments
  FROM sessions
  JOIN subjects ON sessions.subject_id = subjects.subject_id
  JOIN experiment_modes ON sessions.mode_id = experiment_modes.mode_id
  WHERE session_id =
    (SELECT session_id FROM rounds
    WHERE round_id = '", round_id, "')"))
```





```{r pecks_scatterplot, echo=FALSE, fig.width=12, fig.height=8}
# Create a scatterplot to show the position of the pecks using base R

window_width <- session_details$window_width[1]
window_height <- session_details$window_height[1]
button_size <- session_details$button_size[1]
button_height <- session_details$button_height[1]
warning_signal_position <- session_details$warning_signal_position[1]

plot(pecks$x_pos * window_width, pecks$y_pos * window_height,
    xlab = "X Position", ylab = "Y Position",
    main = "Pecks Distribution",
    xlim = c(0, window_width), ylim = c(0, window_height),
    pch = 19, col = "blue", cex = 0.1
) # Adjust the cex parameter to make the dots smaller

# Add circles
symbols((0.3 + (warning_signal_position / 100.0) * 0.4) * window_width, button_height / 100.0 * window_height, circles = button_size / 100.0 / 2.0 * window_height, add = TRUE, inches = FALSE, fg = "red")
symbols(0.7 * window_width, button_height / 100.0 * window_height, circles = button_size / 100.0 / 2.0 * window_height, add = TRUE, inches = FALSE, fg = "green")

# Add additional circles with grace radius if it exists
if (!is.null(session_details$grace_radius)) {
    grace_radius <- session_details$grace_radius * 1080
    symbols((0.3 + (warning_signal_position / 100.0) * 0.4) * window_width, button_height / 100.0 * window_height, circles = button_size / 100.0 / 2.0 * window_height + grace_radius / 100.0, add = TRUE, inches = FALSE, fg = "red", lty = 2)
    symbols(0.7 * window_width, button_height / 100.0 * window_height, circles = button_size / 100.0 / 2.0 * window_height + grace_radius / 100.0, add = TRUE, inches = FALSE, fg = "green", lty = 2)
}
```

\elandscape
